### ISSUE TITLE
Add to flathub?

### ISSUE THREAD

**Issue by nedrichards** [BharatKalluri/bookworm-flatpak#1]
Hey there, this looks pretty cool. [Flathub](https://flathub.org/) can easily host your app if you wish and give access to distribution, builds for x86 and ARM, free bandwidth etc. all whilst still being managed by you.

The only change I can immediately see that [you'd have to make](https://github.com/flathub/flathub/wiki/Review-Guidelines) would be pointing to a release or git tag rather than just the latest commit, but other than that it looks like you already comply with the rest of the review guidelines.

**Comment by BharatKalluri** [comment]
Hello, @nedrichards ,
I had a conversation with the author [(#132)](https://github.com/babluboy/bookworm/issues/132) over at the bookworm repo. He has to make some changes so that the patch file can be completely removed. After That, he will push this to flathub himself.

Cheers!

**Comment by nedrichards** [comment]
Brilliant! That's great to hear.

**Comment by babluboy** [comment]
@nedrichards @BharatKalluri I have made the changes to remove the necessity for the patch and made a release for bookworm. Then using that release in the json I have made a [PR on Flathub](https://github.com/flathub/flathub/pull/138)

Doing this for the first time, so might have made mistakes in how the pr/branches should be set up for flathub. Do let me know in case of any mistakes and I can rectify
